### ISSUE TITLE
clipsToBounds = NO

### ISSUE THREAD

**Issue by craffenoux** [GalacticMegacorp/GMCPagingScrollView#6]
Hello,

Is there a way to preview the prev/next slides with clipsToBounds = NO when the scrollview is smaller than the screen.
Currently the prev/next slide is only displayed when I start dragging.

Many thanks

**Comment by hiltonc** [comment]
Yes, set `numberOfPreloadedPagesOnEachSide` to 1 or greater.

**Comment by craffenoux** [comment]
Thanks!
